project:
  type: book
  output-dir: _book

book:
  title: "Achieving True Freedom"
  subtitle: "An Exploration of the Kitab-i-Aqdas"
  version: "1st Draft"
  author: "Joshua W. Adams"
  reader-mode: true
  date: "12/8/2025"
  downloads: [pdf]
  
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Part1: The Pillars of Belief"
      chapters: 
        - belief in god.qmd
        - belief in the human station.qmd
        - belief in the worlds.qmd
        - belief in the day.qmd
        - belief in the commands of god.qmd
        - belief in the manifestation of god.qmd
    - part: "Part 2: The Relationship with God"
      chapters: 
        - foundational virtues.qmd
        - obligatory prayer.qmd
        - recitation.qmd
        - remembrance.qmd
        - reflection.qmd
        - honoring god.qmd
        - unity.qmd
    - part: "Part 3: Rights and Responsibilities"
      chapters: 
        - from birth to maturity.qmd
        - maturity to devotion.qmd
        - the private self.qmd
        - constructive social life.qmd
        - protective social life.qmd
        - relationships.qmd
        - trusteeship.qmd
        - consultation.qmd
    - part: "Part 4: Leadership After Baha'u'llah"
      chapters: 
        - houses of justice.qmd
        - political leadership.qmd
##        - spiritual leadership.qmd
##        - spiritual successorship.qmd

##        - trusteeship governance.qmd
##        - teaching the cause.qmd

    - part: "Appendices"
      chapters:
        - Appendix 1.qmd
        - Appendix 2.qmd
        - Appendix 3.qmd
        - Appendix 4.qmd
        - Appendix 5.qmd
        - Appendix 6.qmd
        - Appendix 7.qmd
##    - part: "The Kitab-i-Aqdas"
##      chapters: 
##        - kitab-i-aqdas.qmd
##    - summary.qmd
##    - references.qmd

  output-file: "The Aqdas as Life"

## bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    output-file: "The Aqdas as Life"
    fontsize: 11pt
    number-depth: 6
    toc-depth: 1
  docx:
    reference-doc: reference1.docx
    toc-depth: 1
    number-depth: 6

editor: visual

