project:
  type: book
  output-dir: _book

book:
  title: "Achieving True Liberation"
  subtitle: "An Exploration of the Kitab-i-Aqdas"
  author: "Joshua W. Adams"
  date: "2/22/2026"
  downloads: [pdf]
  
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Part 1: The Pillars of Belief"
      chapters: 
        - belief in god.qmd
        - belief in the human soul.qmd
        - belief in the worlds.qmd
        - belief in the day.qmd
        - belief in the commands of god.qmd
        - belief in the manifestation of god.qmd
    - part: "Part 2: The Relationship with God"
      chapters: 
        - foundational virtues.qmd
        - obligatory prayer.qmd
        - recitation.qmd
        - remembrance.qmd
        - reflection.qmd
        - honoring god.qmd
        - unity.qmd
    - part: "Part 3: Rights and Responsibilities"
      chapters: 
        - from birth to maturity.qmd
        - maturity to devotion.qmd
        - the private self.qmd
        - constructive social life.qmd
        - protective social life.qmd
        - relationships.qmd
        - trusteeship.qmd
        - consultation.qmd
    - part: "Part 4: Leadership After Baha'u'llah"
      chapters: 
        - houses of justice.qmd
        - political leadership.qmd
        - spiritual leadership.qmd
        - spiritual successorship.qmd
        - peace.qmd
        - serving the cause.qmd
    - part: "Appendices"
      chapters:
        - Appendix 1.qmd
        - Appendix 9.qmd
        - Appendix 10.qmd
        - Appendix 2.qmd
        - Appendix 3.qmd
        - Appendix 4.qmd
        - Appendix 5.qmd
        - Appendix 6.qmd
        - Appendix 7.qmd
        - Appendix 8.qmd

format:
  html:
    theme: cosmo
  pdf:
    pdf-engine: xelatex
    documentclass: scrbook
    output-file: "Achieving-True-Liberation-Study-of-Aqdas.pdf"
    fontsize: 11pt
    toc-depth: 1
    number-depth: 6
    include-in-header: 
      text: |
        \usepackage{mathpazo} 
        \usepackage[T1]{fontenc}
        \hfuzz=10pt
        \def\mathfamilydefault{\rmdefault}
  docx:
    reference-doc: reference1.docx
    toc-depth: 1
    number-depth: 6

editor: visual